[package]
name = "pingora-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0"

# Try latest stable versions
pingora = "0.6"
pingora-proxy = "0.6"
pingora-load-balancing = "0.6"
